export const ORDER_STATUS_COPY = {
  draft: {
    label: 'Seleção em rascunho',
    description: 'Sua seleção ainda está sendo construída.',
    nextStep: 'Finalize a curadoria quando fizer sentido.',
    severity: 'neutral',
    progressStep: 0,
  },
  awaiting_payment: {
    label: 'Aguardando confirmação',
    description: 'Sua seleção está aguardando confirmação.',
    nextStep: 'Estamos esperando a confirmação segura do pagamento.',
    severity: 'info',
    progressStep: 1,
    canRetryPayment: true,
  },
  pending_payment: {
    label: 'Pagamento pendente',
    description: 'Sua seleção está aguardando confirmação.',
    nextStep: 'Conclua o pagamento ou aguarde a confirmação automática.',
    severity: 'warning',
    progressStep: 1,
    canRetryPayment: true,
  },
  processing_payment: {
    label: 'Pagamento em análise',
    description: 'Estamos confirmando sua seleção com segurança.',
    nextStep: 'A confirmação acontece automaticamente assim que a análise terminar.',
    severity: 'info',
    progressStep: 1,
  },
  paid: {
    label: 'Seleção confirmada',
    description: 'Sua seleção foi confirmada.',
    nextStep: 'Sua curadoria agora entra em preparação.',
    severity: 'success',
    progressStep: 2,
  },
  preparing: {
    label: 'Em preparação',
    description: 'Sua curadoria entrou em preparação.',
    nextStep: 'Estamos preparando sua presença para envio.',
    severity: 'success',
    progressStep: 3,
  },
  shipped: {
    label: 'A caminho',
    description: 'Sua presença está a caminho.',
    nextStep: 'Acompanhe a entrega pelos dados enviados.',
    severity: 'success',
    progressStep: 4,
  },
  delivered: {
    label: 'Entregue',
    description: 'Sua presença foi entregue.',
    nextStep: 'Sua seleção já está com você.',
    severity: 'success',
    progressStep: 5,
  },
  payment_failed: {
    label: 'Pagamento não concluído',
    description: 'Não conseguimos concluir essa direção.',
    nextStep: 'Você pode tentar novamente ou revisar sua seleção.',
    severity: 'danger',
    progressStep: 1,
    canRetryPayment: true,
    canContactSupport: true,
  },
  cancelled: {
    label: 'Seleção cancelada',
    description: 'Essa seleção foi cancelada.',
    nextStep: 'Se quiser, podemos reconstruir sua seleção com calma.',
    severity: 'muted',
    progressStep: 0,
    canContactSupport: true,
  },
  refunded: {
    label: 'Reembolso registrado',
    description: 'O reembolso dessa seleção foi registrado.',
    nextStep: 'Nosso suporte pode acompanhar qualquer detalhe adicional.',
    severity: 'warning',
    progressStep: 1,
    canContactSupport: true,
  },
  chargeback: {
    label: 'Contestação registrada',
    description: 'Essa seleção entrou em contestação de pagamento.',
    nextStep: 'Nosso suporte acompanha a tratativa com segurança.',
    severity: 'danger',
    progressStep: 1,
    canContactSupport: true,
  },
};

export const ORDER_STATUSES = Object.freeze(Object.keys(ORDER_STATUS_COPY));
